title: UB Business Doctorands
description: Home of UB doctoral researchers in Business

url: http://businessdoctorands.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Activities
   url: /activities  
 - title: Contact
   url: /contact
 - title: Upcoming Events
   url: /events 

collections:
   events:
    output: true 
    permalink: /events/:path/:title

social:
   github: businessdoctorands
   twitter: ryan_kwan_do
   facebook: groups/697965583666993
   email: ryarmsta7@alumnes.ub.edu

google_analytics: ""
