title: UB Business Doctorands
description: Home of UB doctoral researchers in Business

url: http://businessdoctorands.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Activities
   url: /activities  
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: ryan_kwan_do
   facebook: brianmaierjr
   email: ryarmsta7@alumnes.ub.edu

google_analytics: ""
